include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these specific warnings as errors
    invalid_annotation_target: error
    invalid_use_of_visible_for_testing_member: error
    # All other issues will be treated as warnings
    deprecated_member_use: ignore
    avoid_web_libraries_in_flutter: ignore
    use_build_context_synchronously: ignore
    curly_braces_in_flow_control_structures: ignore
    file_names: ignore
    unnecessary_breaks: ignore
    non_constant_identifier_names: ignore
    unnecessary_brace_in_string_interps: ignore

linter:
  rules:
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    unnecessary_breaks: true
    use_key_in_widget_constructors: false